## Site settings
title: GDG Lisboa
title_min: GDGLx
email: lisbon.gdg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Google Developer Group Lisboa.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gdg-lisbon.github.io/website/" # the base hostname & protocol for your site
url_dev: "http://localhost:4000"
twitter_username: GDGLisbon
github_username:  GDG-Lisbon

# Build settings
markdown: kramdown
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

pages:
  - title: Home
    url: /
  - title: Eventos
    url: /eventos
  - title: Sobre GDG
    url: /sobre


exclude: ['package.json', '_src', 'node_modules', 'vendor/bundle/ruby']
